export const LANG_ACTION = {
    SWITCH_LANGUAGE : 'SWITCH_LANGUAGE',
    FETCH_LANGUAGES : 'FETCH_LANGUAGES'
}

export const PRODUCT_ACTION = {
    FETCH_PRODUCTS_BEGIN: 'FETCH_PRODUCTS_BEGIN',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE'
}

export const PRODUCT_CATEGORY_ACTION = {
    FETCH_PRODUCT_CATEGORY_BEGIN: 'FETCH_PRODUCT_CATEGORY_BEGIN',
    FETCH_PRODUCT_CATEGORY_SUCCESS: 'FETCH_PRODUCT_CATEGORY_SUCCESS',
    FETCH_PRODUCT_CATEGORY_FAILURE: 'FETCH_PRODUCT_CATEGORY_FAILURE'
}