export const LANG_ACTION = {
    SWITCH_LANGUAGE : 'SWITCH_LANGUAGE',
    FETCH_LANGUAGES : 'FETCH_LANGUAGES'
}

export const PRODUCT_ACTION = {
    FETCH_PRODUCTS_BEGIN: 'FETCH_PRODUCTS_BEGIN',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE'
}

export const PRODUCT_CATEGORY_ACTION = {
    SWITCH_PRODUCT_CATEGORY : 'SWITCH_PRODUCT_CATEGORY',
    FETCH_PRODUCT_CATEGORY_BEGIN: 'FETCH_PRODUCT_CATEGORY_BEGIN',
    FETCH_PRODUCT_CATEGORY_SUCCESS: 'FETCH_PRODUCT_CATEGORY_SUCCESS',
    FETCH_PRODUCT_CATEGORY_FAILURE: 'FETCH_PRODUCT_CATEGORY_FAILURE'
}

export const BREADCRUMS_ACTION = {
    ADD_BREADCRUMS: 'ADD_BREADCRUMS'
}

export const LIMIT_ACTION = {
    LOAD_LIMIT : 'LOAD_LIMIT',
    CHANGE_LIMIT : 'CHANGE_LIMIT',
    RESET_LIMIT: 'RESET_LIMIT'
}

export const FILTER_ACTION = {
    CHANGE_FILTER: 'CHANGE_FILTER'
}