export const LANG_ACTION = {
    SWITCH_LANGUAGE : 'SWITCH_LANGUAGE',
    FETCH_LANGUAGES : 'FETCH_LANGUAGES'
}

export const PRODUCT_ACTION = {
    FETCH_PRODUCTS_BEGIN: 'FETCH_PRODUCTS_BEGIN',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE'
}